import type { CatalogEntry } from './types';

/**
 * Known diagnostic codes. Templates only interpolate keys present in live `facts`.
 * tradingBlocked is the catalog default; DiagnosticService may override from RiskEngine.
 */
export const DIAGNOSTIC_CATALOG: Record<string, CatalogEntry> = {
  'MD-001': {
    code: 'MD-001',
    component: 'MARKET_DATA',
    severity: 'ERROR',
    status: 'DATA_STALE',
    title: 'Market data is stale',
    userMessage: 'Price data for {symbol} has not updated for {ageSeconds} seconds. RiskEngine blocks new orders when a quote is older than {thresholdSeconds} seconds.',
    cause: '{cause}',
    impact: 'New BUY/SELL entries that need a live quote cannot pass the data_freshness gate.',
    tradingImpact: 'NEW ORDERS BLOCKED until a fresh tick arrives. Open positions are still monitored if a last price exists.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Check the Alpaca market-data WebSocket. Confirm ALPACA_API_KEY / ALPACA_SECRET_KEY and that the market session is open for the subscribed symbols.',
    troubleshootingSteps: [
      'Confirm MarketDataWorker reports the WebSocket OPEN.',
      'Confirm Alpaca keys are set (values are never displayed).',
      'Check whether US equities are in session if you expect sub-second ticks.',
      'Retry the market-data reconnect from Diagnostics.',
    ],
    documentationReference: 'CLAUDE.md — RiskEngine data_freshness (>5 min)',
    retryable: true,
    autoRecoveryAvailable: true,
  },
  'MD-002': {
    code: 'MD-002',
    component: 'MARKET_DATA',
    severity: 'WARNING',
    status: 'MISCONFIGURED',
    title: 'Alpaca market-data keys are not configured',
    userMessage: 'MarketDataWorker is idle because ALPACA_API_KEY or ALPACA_SECRET_KEY is unset. No ticks are being fabricated.',
    cause: 'Missing Alpaca credentials in the server environment.',
    impact: 'Live quote stream is off. Agents that require MARKET_DATA will not emit ideas from ticks.',
    tradingImpact: 'The live tick pipeline is inactive. Paper InternalPaperBroker can still simulate fills if an order is somehow approved, but RiskEngine refuses invalid/missing prices.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Set ALPACA_API_KEY and ALPACA_SECRET_KEY in .env (never paste keys into chat or the UI).',
    troubleshootingSteps: ['Copy .env.example to .env', 'Add Alpaca paper keys', 'Restart Argus'],
    documentationReference: 'CLAUDE.md — Environment Setup',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'MD-003': {
    code: 'MD-003',
    component: 'MARKET_DATA',
    severity: 'INFO',
    status: 'AVAILABLE',
    title: 'Market data feed is receiving ticks',
    userMessage: 'Alpaca WebSocket is OPEN. Last tick age {ageSeconds}s. Coverage is top-of-book (trade/quote), not L2 depth.',
    cause: 'Live Alpaca IEX/SIP top-of-book stream as implemented in MarketDataWorker.',
    impact: 'Tick-driven agents can run. L2 order-book strategies remain unavailable because no L2 source exists in this codebase.',
    tradingImpact: 'Not blocked by market-data connectivity.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'None required for top-of-book strategies.',
    troubleshootingSteps: [],
    documentationReference: 'CLAUDE.md — Known Broken: L2 depth',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'MD-005': {
    code: 'MD-005',
    component: 'MARKET_DATA',
    severity: 'ERROR',
    status: 'UNAVAILABLE',
    title: 'Alpaca market-data WebSocket is not OPEN',
    userMessage: '{cause}',
    cause: '{cause}',
    impact: 'No live ticks. RiskEngine data_freshness cannot pass without a quote newer than {thresholdSeconds} seconds.',
    tradingImpact: 'NEW ORDERS BLOCKED until the WebSocket is OPEN and a fresh tick arrives. This page does not bypass RiskEngine.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Confirm ALPACA_API_KEY / ALPACA_SECRET_KEY. npm run dev starts the feed at boot even if Autobot is off. Use Retry probe (MARKET_DATA). Values are never displayed.',
    troubleshootingSteps: [
      'Confirm MarketDataWorker readyState in the retry response (0=CONNECTING, 1=OPEN).',
      'If lastError is an Alpaca auth/subscription error, the keys or stream URL are wrong — do not fabricate ticks.',
      'US equities being closed does not by itself prevent the socket from opening; it only means quotes may be silent.',
      'Retry the market-data reconnect from Diagnostics.',
    ],
    documentationReference: 'CLAUDE.md — RiskEngine data_freshness (>5 min)',
    retryable: true,
    autoRecoveryAvailable: true,
  },
  'MD-006': {
    code: 'MD-006',
    component: 'MARKET_DATA',
    severity: 'WARNING',
    status: 'DATA_STALE',
    title: 'US regular session is closed (Alpaca clock)',
    userMessage: 'Alpaca /v2/clock reports the market is {clockStatus}. The WebSocket can still be OPEN, but RiskEngine market_hours blocks new entries until the next regular session. Last tick age: {ageSeconds}.',
    cause: 'Alpaca market clock is closed (or unavailable, which fail-closes). Not a fabricated session.',
    impact: 'New BUY/SELL entries fail the market_hours gate. This is expected overnight and on weekends.',
    tradingImpact: 'NEW ORDERS BLOCKED by RiskEngine market_hours. Open positions are still monitored if a last price exists. Do not bypass the gate.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Wait for the next US regular session. If clockStatus is unavailable, restore Alpaca REST connectivity — an outage fail-closes.',
    troubleshootingSteps: [
      'Check America/New_York session hours',
      'Confirm Alpaca paper/live keys can call GET /v2/clock',
    ],
    documentationReference: 'CLAUDE.md — RiskEngine market_hours',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'MD-004': {
    code: 'MD-004',
    component: 'MARKET_DATA',
    severity: 'INFO',
    status: 'DATA_MISSING',
    title: 'Level 2 order book is not available',
    userMessage: 'No L2 market-data adapter exists. Alpaca IEX in this app is top-of-book only. This is a missing capability, not a crashed service.',
    cause: 'No L2 provider is implemented.',
    impact: 'L2-dependent UI (depth heatmap) cannot show a real ladder.',
    tradingImpact: 'Does not block the existing RiskEngine path. Those strategies were never wired.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Do not enable L2 strategies. A paid L2 feed would be new work, not a config toggle.',
    troubleshootingSteps: [],
    documentationReference: 'CLAUDE.md — Order Book (L2)',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'CFG-001': {
    code: 'CFG-001',
    component: 'FUNDAMENTAL',
    severity: 'WARNING',
    status: 'MISCONFIGURED',
    title: 'ALPHAVANTAGE_API_KEY is not configured',
    userMessage: 'FundamentalAgent and MacroAgent read Alpha Vantage. The key is absent, so those agents emit DATA_UNAVAILABLE (confidence 0) instead of fabricating fundamentals.',
    cause: 'ALPHAVANTAGE_API_KEY is unset.',
    impact: 'Fundamental/Macro evidence will not contribute directional votes (HOLD at confidence 0 does not dilute consensus).',
    tradingImpact: 'Not blocked. ChiefTrader still requires other independent agents. This is optional evidence.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Add ALPHAVANTAGE_API_KEY to the server environment if you want fundamental/macro evidence. Do not put the key in the UI.',
    troubleshootingSteps: ['Edit .env on the server', 'Restart Argus', 'Confirm FundamentalAgent no longer logs DATA_UNAVAILABLE: not configured'],
    documentationReference: 'CLAUDE.md — Environment Setup',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'NEWS-001': {
    code: 'NEWS-001',
    component: 'NEWS',
    severity: 'INFO',
    status: 'EMPTY_RESULT',
    title: 'News service is online; no matching articles in this window',
    userMessage: 'News providers are registered. No stored article matched the requested symbol/window. This is an empty result, not an outage.',
    cause: 'Query returned zero rows from news_articles for the filter.',
    impact: 'News evidence is absent for this symbol/window. Other agents are unaffected.',
    tradingImpact: 'Not an error. Do not configure a new API key solely because no article matched.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Widen the time window or wait for the next ingest cycle.',
    troubleshootingSteps: ['Confirm RSS/API providers are listed as configured', 'Check news_articles timestamps', 'Do not treat this as NEWS-002'],
    documentationReference: null,
    retryable: true,
    autoRecoveryAvailable: false,
  },
  'NEWS-002': {
    code: 'NEWS-002',
    component: 'NEWS',
    severity: 'WARNING',
    status: 'MISCONFIGURED',
    title: 'A paid news provider is not configured',
    userMessage: 'Provider {provider} requires an API key that is not set. RSS providers (if registered) may still ingest headlines.',
    cause: '{provider} isConfigured() is false.',
    impact: 'That provider will not fetch. Other registered providers still run.',
    tradingImpact: 'Optional. NewsAgent still runs on whatever providers are configured.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Set the provider key in .env if you want that feed. Keys are never shown here.',
    troubleshootingSteps: ['Identify which paid provider is listed', 'Add its env var', 'Restart Argus'],
    documentationReference: 'CLAUDE.md — FINNHUB_API_KEY note',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'MOD-001': {
    code: 'MOD-001',
    component: 'CHRONOS',
    severity: 'WARNING',
    status: 'UNAVAILABLE',
    title: 'Chronos/Kronos local inference is not responding',
    userMessage: 'The local inference service at {endpoint} did not answer /health ({detail}). Chronos/Kronos forecasting cannot run until it does.',
    cause: '{detail}',
    impact: 'KronosForecastAgent will not produce a forecast. Other agents continue.',
    tradingImpact: 'OPTIONAL provider. New trades are NOT blocked solely because Chronos is down. Kronos evidence is excluded from consensus.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'npm run dev starts Chronos (scripts/local_ai_service.py on 127.0.0.1:8008). If /health still fails: Python 3.10+, npm run setup:ai, or npm run ai:serve. Skip with ARGUS_SKIP_CHRONOS=true.',
    troubleshootingSteps: [
      'Confirm nothing else is bound to the configured port',
      'Use http://127.0.0.1:8008 (not localhost) if Windows IPv6 localhost fails',
      'Retry the probe from Diagnostics',
      'Skip auto-start with ARGUS_SKIP_CHRONOS=true if you do not want the model loaded',
    ],
    documentationReference: 'docs/LOCAL_AI_SETUP.md',
    retryable: true,
    autoRecoveryAvailable: true,
  },
  'MOD-002': {
    code: 'MOD-002',
    component: 'OLLAMA',
    severity: 'WARNING',
    status: 'UNAVAILABLE',
    title: 'Ollama is not reachable',
    userMessage: 'Ollama at {endpoint} did not answer /api/tags ({detail}). Local LLM reasoning is unavailable; AIRouter can still use configured cloud providers.',
    cause: '{detail}',
    impact: 'Local $0 models will not be used. Cloud providers remain if their keys are set.',
    tradingImpact: 'OPTIONAL. Trading is not blocked solely because Ollama is down.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Install Ollama, run ollama serve, or set ARGUS_START_LOCAL_MODELS=true.',
    troubleshootingSteps: ['curl {endpoint}/api/tags', 'Run ollama serve', 'Retry probe'],
    documentationReference: 'docs/LOCAL_AI_SETUP.md',
    retryable: true,
    autoRecoveryAvailable: true,
  },
  'MOD-003': {
    code: 'MOD-003',
    component: 'OPENALICE',
    severity: 'INFO',
    status: 'OPTIONAL_DISABLED',
    title: 'OpenAlice verification is disabled',
    userMessage: '{detail}',
    cause: 'OPENALICE_ENABLED is not true or OPENALICE_MCP_URL is unset.',
    impact: 'No independent second-opinion requests are filed. ChiefTrader approvals are unchanged.',
    tradingImpact: 'OPTIONAL and non-blocking by design. OpenAlice never authorizes or blocks a live order.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Set OPENALICE_ENABLED=true and OPENALICE_MCP_URL only if an OpenAlice instance exists.',
    troubleshootingSteps: [],
    documentationReference: 'docs/archive/historical/OPENALICE_INTEGRATION_AUDIT.md',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'MOD-004': {
    code: 'MOD-004',
    component: 'OPENALICE',
    severity: 'WARNING',
    status: 'UNAVAILABLE',
    title: 'OpenAlice is enabled but unreachable',
    userMessage: '{detail}',
    cause: '{detail}',
    impact: 'Verification requests will time out. They still must not block RiskEngine.',
    tradingImpact: 'OPTIONAL. Live orders are not blocked by OpenAlice failure.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Start OpenAlice Guardian (npm run dev waits for http://127.0.0.1:47332/mcp). Point OPENALICE_MCP_URL at that Guardian URL (issue_create + inbox_read). A trading MCP with placeOrder is the wrong server. Skip with ARGUS_SKIP_OPENALICE=true or ENABLE_OPENALICE=false.',
    troubleshootingSteps: ['Confirm MCP URL (never log secrets)', 'Retry health'],
    documentationReference: 'docs/archive/historical/OPENALICE_INTEGRATION_AUDIT.md',
    retryable: true,
    autoRecoveryAvailable: false,
  },
  'MOD-005': {
    code: 'MOD-005',
    component: 'CHRONOS',
    severity: 'INFO',
    status: 'DATA_MISSING',
    title: 'Chronos/Kronos cannot forecast: insufficient history',
    userMessage: 'The inference service is reachable, but this symbol has {availableBars} bars; the agent requires at least {requiredBars}. No forecast was produced.',
    cause: 'Sequence length below the model/agent minimum. Not a crash.',
    impact: 'This symbol is excluded from Kronos evidence until more bars exist.',
    tradingImpact: 'OPTIONAL exclusion. Other evidence sources still apply.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Widen the historical window or wait for more live ticks to accumulate.',
    troubleshootingSteps: ['Check ohlcv_bars row count for the symbol', 'Confirm HistoricalDataGateway can fetch'],
    documentationReference: 'docs/LOCAL_AI_SETUP.md',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'CAP-001': {
    code: 'CAP-001',
    component: 'CAPITAL',
    severity: 'ERROR',
    status: 'UNAVAILABLE',
    title: 'Order blocked by Argus allocation, not by the broker',
    userMessage: 'Requested ${requested} but Argus remaining allocation is ${remaining} of ${allocated} (already used ${used}). Broker buying power is ${brokerBuyingPower} and is NOT the reason.',
    cause: 'argus_capital_allocation gate failed. Argus authority is a slice of the broker account.',
    impact: 'This BUY was not submitted to the broker.',
    tradingImpact: 'THIS ORDER BLOCKED BY ARGUS. Other symbols may still trade if they fit remaining allocation.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Lower the order size, wait for a SELL to free allocation, or raise settings.budget (Allocated Budget Limit) if you intend a larger Argus slice.',
    troubleshootingSteps: [
      'Compare Argus remaining vs requested — if remaining < requested, Argus blocked it',
      'If remaining >= requested, this code must not be used; look at the broker reject instead',
    ],
    documentationReference: 'ARGUS_PHASE_NEXT_ORCHESTRATION_REPORT.md',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'RSK-001': {
    code: 'RSK-001',
    component: 'RISK_ENGINE',
    severity: 'ERROR',
    status: 'UNAVAILABLE',
    title: 'Trade blocked by RiskEngine',
    userMessage: 'Failed gate: {gate}. {reasoning}',
    cause: '{gate}',
    impact: 'OrderManagement did not place this order.',
    tradingImpact: 'THIS ENTRY BLOCKED. Existing positions continue to be monitored independently.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: '{recommendedFix}',
    troubleshootingSteps: ['Inspect risk_gate_results for this traceId', 'Do not ask an LLM whether to ignore the gate'],
    documentationReference: 'CLAUDE.md — RiskEngine',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'BRK-001': {
    code: 'BRK-001',
    component: 'BROKER',
    severity: 'ERROR',
    status: 'UNAVAILABLE',
    title: 'Broker rejected or failed an order',
    userMessage: '{detail}',
    cause: '{detail}',
    impact: 'The broker did not accept/fill as requested. Argus allocation may still be reserved until the PENDING row is terminal.',
    tradingImpact: 'THIS ORDER failed at the broker. Distinct from CAP-001 (Argus allocation).',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Read the broker error. Typical causes: buying power, market closed, invalid qty, authentication.',
    troubleshootingSteps: ['Check broker dashboard', 'Confirm paper vs live mode', 'Do not blame Argus allocation if this code fired'],
    documentationReference: 'CLAUDE.md — Broker Layer',
    retryable: true,
    autoRecoveryAvailable: false,
  },
  'BT-001': {
    code: 'BT-001',
    component: 'BACKTEST',
    severity: 'ERROR',
    status: 'DATA_MISSING',
    title: 'Backtest blocked: insufficient real bars',
    userMessage: '{detail}',
    cause: 'Not enough OHLCV bars in the requested range.',
    impact: 'No simulated trades were produced for this run. Results were not fabricated.',
    tradingImpact: 'Live/paper trading is unaffected.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Widen the date range or ensure HistoricalDataGateway can fetch bars for the symbol.',
    troubleshootingSteps: ['Confirm Alpaca keys for backfill', 'Check ohlcv_bars'],
    documentationReference: 'LIVE_BACKTEST_PARITY_SPEC.md',
    retryable: true,
    autoRecoveryAvailable: false,
  },
  'BT-002': {
    code: 'BT-002',
    component: 'BACKTEST',
    severity: 'CRITICAL',
    status: 'DATA_MISSING',
    title: 'Backtest blocked: corporate-action / split inconsistency',
    userMessage: '{detail}',
    cause: 'Unadjusted split or corporate action would corrupt PnL if the run continued.',
    impact: 'Backtest stopped to prevent corrupted results.',
    tradingImpact: 'Live/paper trading is unaffected. Do not treat a blocked backtest as a live failure.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Use split-adjusted historical bars on the main historical data path.',
    troubleshootingSteps: ['Inspect the CORPORATE_ACTION_DETECTED detail', 'Re-fetch adjusted bars'],
    documentationReference: 'LIVE_BACKTEST_PARITY_SPEC.md',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'SYS-001': {
    code: 'SYS-001',
    component: 'SYSTEM',
    severity: 'CRITICAL',
    status: 'UNAVAILABLE',
    title: 'Emergency stop or trading pause is active',
    userMessage: 'tradingState is {tradingState}. New trades are blocked until an operator resumes.',
    cause: '{tradingState}',
    impact: 'RiskEngine emergency_stop gate fails for every new proposal.',
    tradingImpact: 'NEW ORDERS BLOCKED. Existing positions are not automatically flattened unless emergency-stop cancel-open-orders ran.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Use POST /api/v1/system/resume only after reviewing why trading was halted.',
    troubleshootingSteps: ['Read kill_switch_events', 'Confirm it was intentional'],
    documentationReference: 'CLAUDE.md — TradingEngine',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'SYS-002': {
    code: 'SYS-002',
    component: 'SYSTEM',
    severity: 'WARNING',
    status: 'UNAVAILABLE',
    title: 'Autobot is off',
    userMessage: 'TradingEngine.enabled is false (Autobot disabled). The kill switch tradingState is {tradingState}. Market data may still run; new autonomous entries will not.',
    cause: 'autoBotEnabled is false in settings.',
    impact: 'The EventBus agent loop that emits trade ideas from Autobot is idle.',
    tradingImpact: 'NEW AUTONOMOUS ENTRIES will not be proposed until Autobot is enabled. RiskEngine is not bypassed if a manual override is used.',
    tradingBlocked: true,
    canContinueSafely: true,
    recommendedFix: 'Enable Autobot from Command Center only if you intend the live path to run. This does not resume an EMERGENCY_STOP.',
    troubleshootingSteps: ['Confirm tradingState is TRADING_ENABLED before enabling Autobot', 'Do not treat Diagnostics retry as an Autobot start'],
    documentationReference: 'CLAUDE.md — TradingEngine',
    retryable: false,
    autoRecoveryAvailable: false,
  },
  'AI-001': {
    code: 'AI-001',
    component: 'AI_ROUTER',
    severity: 'WARNING',
    status: 'DEGRADED',
    title: 'AI provider failover',
    userMessage: 'Provider {fromProvider} failed ({reason}). Request was sent to {toProvider} instead.',
    cause: '{reason}',
    impact: 'Reduced provider diversity for this call. Deterministic agents are unchanged.',
    tradingImpact: 'Does not by itself approve or reject a trade. RiskEngine still runs.',
    tradingBlocked: false,
    canContinueSafely: true,
    recommendedFix: 'Inspect the failed provider health (expired key, timeout, local process down).',
    troubleshootingSteps: ['Check ai_providers.health', 'Do not treat failover as a silent success of the first model'],
    documentationReference: 'CLAUDE.md — AIRouter',
    retryable: true,
    autoRecoveryAvailable: false,
  },
};

export const GATE_FIX: Record<string, string> = {
  emergency_stop: 'Resume trading only after reviewing kill-switch events.',
  autobot_enabled: 'Turn Autobot on (POST /autobot/toggle) before taking new BUY risk. SELL/exits still run while TRADING_ENABLED.',
  same_symbol_cooldown: 'Wait for sameSymbolCooldownMs after the last FILLED order in this symbol.',
  post_loss_cooldown: 'Wait for postLossCooldownMs after a closed losing SELL.',
  daily_trade_limit: 'Wait for the next America/New_York session or raise maxDailyTrades in tradingSafety.json after review.',
  duplicate_signal: 'A BUY for this symbol was already assessed inside duplicateSignalWindowMs.',
  daily_loss: 'Wait for the next exchange trading day or raise dailyLossLimit after a human review.',
  consecutive_loss: 'Review the last three closed SELL P&L rows before re-enabling aggressive entries.',
  portfolio_drawdown: 'Drawdown from peak equity exceeded the configured cap. Manual review required.',
  order_rate_limit: 'Wait until fewer than maxOrdersPerMinute proposals hit RiskEngine.',
  market_hours: 'Wait for the regular session. If the Alpaca clock request failed, restore API connectivity — an outage fail-closes this gate. Unconfigured keys skip the check.',
  data_freshness: 'Restore the market-data WebSocket so quotes are newer than 5 minutes.',
  news_veto: 'A high-impact news cluster in the last 4 hours vetoed this symbol (direction-blind).',
  price_validity: 'A finite live price is required. No fabricated price will be used.',
  open_positions_cap: 'Close or reduce an existing position before opening a new symbol.',
  sufficient_size: 'Buying power, maxTradeSize, or concentration caps produced zero shares.',
  sell_position_exists: 'Cannot SELL a symbol the broker does not hold.',
  argus_capital_allocation: 'Reduce notional or free Argus allocation. Broker cash is irrelevant if remaining allocation is too small.',
  daily_buy_notional: 'Wait for the next America/New_York trading day or reduce BUY size. This cap is cumulative BUY dollars, not the daily-loss kill-switch.',
};
