const fs = require('fs');
const path = '/app/applet/src/components/KronosDashboard.tsx';
let content = fs.readFileSync(path, 'utf8');

content = content.replace(
  'import { BrainCircuit, Activity, Database, Clock, RefreshCw, AlertTriangle, Settings2, BarChart2 } from "lucide-react";',
  `import { BrainCircuit, Activity, Database, Clock, RefreshCw, AlertTriangle, Settings2, BarChart2, ActivitySquare } from "lucide-react";\nimport { ComposedChart, Line, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";\n\nconst mockVolatilityData = Array.from({ length: 40 }).map((_, i) => {\n  const isPrediction = i >= 30;\n  const basePrice = 45000 + Math.sin(i * 0.2) * 500 + (i * 20);\n  const atr = 150 + (isPrediction ? (i - 30) * 25 : Math.random() * 50);\n  \n  return {\n    time: \`\${9 + Math.floor(i / 6).toString().padStart(2, '0')}:\${(i % 6) * 10 || '00'}\`,\n    price: isPrediction ? null : basePrice,\n    predictedPrice: isPrediction ? basePrice : null,\n    upperBand: basePrice + atr * 2,\n    lowerBand: basePrice - atr * 2,\n    isPrediction\n  };\n});`
);

content = content.replace(
  '             </div>\n          </div>\n      </div>\n    </div>\n  );\n};',
  `             </div>\n          </div>\n      </div>\n\n      <div className="bg-[#1A1F2B] border border-slate-800 rounded-lg p-6">\n        <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2 border-b border-slate-800 pb-4">\n          <ActivitySquare size={16} className="text-indigo-400" />\n          Kronos Volatility & Price Forecast (ATR Bands)\n        </h2>\n        <div className="h-72 w-full mt-4">\n          <ResponsiveContainer width="100%" height="100%">\n            <ComposedChart data={mockVolatilityData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>\n              <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.4} />\n              <XAxis dataKey="time" stroke="#64748b" fontSize={10} tickMargin={10} />\n              <YAxis stroke="#64748b" fontSize={10} domain={['auto', 'auto']} tickFormatter={(val) => \`$\${val.toLocaleString()}\`} />\n              <Tooltip \n                contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', borderRadius: '8px' }}\n                itemStyle={{ fontSize: '12px' }}\n                labelStyle={{ color: '#94a3b8', fontSize: '12px', marginBottom: '4px' }}\n              />\n              <Area type="monotone" dataKey="upperBand" stroke="none" fill="#3b82f6" fillOpacity={0.05} />\n              <Area type="monotone" dataKey="lowerBand" stroke="none" fill="#3b82f6" fillOpacity={0.05} />\n              <Line type="monotone" dataKey="price" stroke="#10b981" strokeWidth={2} dot={false} name="Actual Price" />\n              <Line type="monotone" dataKey="predictedPrice" stroke="#a78bfa" strokeWidth={2} strokeDasharray="5 5" dot={false} name="Kronos Forecast" />\n            </ComposedChart>\n          </ResponsiveContainer>\n        </div>\n        <div className="flex items-center justify-center gap-6 mt-4 text-xs">\n          <div className="flex items-center gap-2 text-slate-400">\n            <div className="w-3 h-3 rounded-full bg-emerald-500"></div> Historical\n          </div>\n          <div className="flex items-center gap-2 text-slate-400">\n            <div className="w-3 h-3 rounded-full bg-purple-400 border border-purple-400/50 border-dashed"></div> Forecast\n          </div>\n          <div className="flex items-center gap-2 text-slate-400">\n            <div className="w-3 h-3 rounded bg-blue-500/20 border border-blue-500/40"></div> 2.0 ATR Bands\n          </div>\n        </div>\n      </div>\n    </div>\n  );\n};\n`
);

fs.writeFileSync(path, content, 'utf8');
console.log('Successfully patched KronosDashboard.tsx');
