import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';
import express from 'express';
import request from 'supertest';
import { eq } from 'drizzle-orm';

/**
 * Real integration test (isolated temp SQLite DB, real Express router via supertest) for
 * GET /api/v2/agents/learning-summary - the real replacement for the Learning & Evolution tab's
 * fabricated "Mistakes Corrected"/"Models Retrained"/"Alpha Generated by RL" figures, invented
 * "PER-STRATEGY SCORECARD" (Trend-Following/Political Intel), fake Kelly-sizing learner, and
 * scripted "Post-Trade Post-Mortem" narrative. Proves the route returns real per-agent weights
 * (honestly null win rate for agents with no real evaluated history, matching the placeholder-row
 * lesson from Task 3 of this pass) and real learned_rules text.
 */
describe('GET /api/v2/agents/learning-summary', () => {
  let tmpDbPath: string;
  let db: any;
  let sqliteDb: any;
  let schema: any;
  let app: express.Express;

  beforeAll(async () => {
    tmpDbPath = path.join(os.tmpdir(), `argus_v2learning_${Date.now()}_${process.pid}.db`);
    process.env.ARGUS_DB_PATH = tmpDbPath;

    ({ db, sqliteDb } = await import('../db'));
    schema = await import('../db/schema');

    const { v2Router } = await import('./v2System');
    app = express();
    app.use(express.json());
    app.use('/api/v2', v2Router);
  });

  afterAll(() => {
    try { sqliteDb.close(); } catch { /* already closed */ }
    for (const suffix of ['', '-shm', '-wal']) {
      try { fs.unlinkSync(tmpDbPath + suffix); } catch { /* best-effort cleanup */ }
    }
    delete process.env.ARGUS_DB_PATH;
  });

  it('reports real per-agent weight for all 5 real agents, honestly null win rate before any real evaluation, and real learned rule text', async () => {
    // Update NewsAgent's real placeholder row (seeded by ChiefTraderAgent.syncWeights()) to a
    // real evaluated state, exactly like ReflectionEngine's own real evaluateAgents() would.
    await db.update(schema.agentPerformanceStats)
      .set({ totalPredictions: 10, correctPredictions: 6, winRate: 0.6, currentWeight: 0.32 })
      .where(eq(schema.agentPerformanceStats.agentName, 'NewsAgent'));

    await db.insert(schema.learnedRules).values({
      id: 'rule-1', agent: 'NewsAgent', cause: 'Overconfident on low-liquidity tickers',
      rule: 'Reduce confidence by 15% for symbols with <1M daily volume.', confidence: 0.7,
      timestamp: new Date().toISOString(),
    });

    const res = await request(app).get('/api/v2/agents/learning-summary');
    expect(res.status).toBe(200);
    expect(res.body.ok).toBe(true);

    expect(res.body.agentWeights.map((a: any) => a.agentName)).toEqual([
      'TechnicalAgent', 'NewsAgent', 'FundamentalAgent', 'MacroAgent', 'KronosForecastAgent',
    ]);

    const news = res.body.agentWeights.find((a: any) => a.agentName === 'NewsAgent');
    expect(news.currentWeight).toBe(0.32);
    expect(news.winRate).toBe(60);

    const technical = res.body.agentWeights.find((a: any) => a.agentName === 'TechnicalAgent');
    expect(technical.winRate).toBeNull(); // still just a placeholder row, no real evaluation yet

    expect(res.body.recentLearnedRules).toHaveLength(1);
    expect(res.body.recentLearnedRules[0].rule).toBe('Reduce confidence by 15% for symbols with <1M daily volume.');
  });
});
