from typing import Dict, Any, List, Optional
import uuid
from domain.entities import Trade, TradeStatus, Position, RiskEvent, OrderSide, OrderType
from core.config import settings

class PositionSizingAgent:
    """
    Computes secure allocation sizing for new trades.
    Uses default_trade_size ($100 as base limit), confidence curves, or Kelly Criterion models.
    """
    def __init__(self, default_size: float = 100.0, max_size: float = 5000.0):
        self.default_size = default_size
        self.max_size = max_size

    def calculate_size(self, confidence: float, symbol: str, active_cash: float, use_kelly: bool = False) -> float:
        """
        Calculates trade size. Leverages trade confidence as multiplier.
        """
        if active_cash <= self.default_size:
            return 0.0 # Insufficient cash
            
        if use_kelly:
            # Custom conservative Kelly: p = confidence, q = 1-p, win/loss ratio b = 1
            # Kelly Fraction f* = p - q = 2p - 1
            win_prob = confidence
            lose_prob = 1.0 - confidence
            fraction = max(0.0, win_prob - lose_prob)
            kelly_size = fraction * active_cash * 0.1 # Max leverage safeguard of 10% cash
            return float(min(self.max_size, max(self.default_size, kelly_size)))
            
        # Confidence-adjusted sizing: scaling up to 1.5x of default_size
        multiplier = 1.0
        if confidence > 0.8:
            multiplier = 1.4
        elif confidence < 0.6:
            multiplier = 0.8
            
        calculated = self.default_size * multiplier
        return float(min(self.max_size, calculated))

class ExposureAgent:
    """
    Enforces diversification limits (e.g. limit sector concentrations to max 35%).
    """
    def __init__(self, max_sector_limit: float = 0.35):
        self.max_sector_limit = max_sector_limit

    def valuate_exposure_limit(self, symbol: str, sector: str, candidate_amount: float, active_positions: List[Position], total_portfolio_equity: float) -> tuple[bool, str]:
        sector_capital = candidate_amount
        for pos in active_positions:
            if pos.sector.lower() == sector.lower():
                sector_capital += pos.market_value
                
        allocated_pct = sector_capital / (total_portfolio_equity + 0.001)
        if allocated_pct > self.max_sector_limit:
            return False, f"Sector exposure breach. Sector '{sector}' would reach {allocated_pct * 100:.1f}%, exceeding safety ceiling of {self.max_sector_limit * 100:.1f}%."
            
        return True, "Sector limit cleared."

class CorrelationAgent:
    """
    Ensures active positions aren't overly correlated, preventing compounding market risks.
    """
    def __init__(self):
        # High static correlations lookup
        self._correlation_matrix = {
            ("NVDA", "AMD"): 0.88,
            ("AAPL", "MSFT"): 0.72,
            ("XOM", "CVX"): 0.82
        }

    def check_correlation(self, symbol: str, active_positions: List[Position]) -> tuple[bool, str]:
        for pos in active_positions:
            pair = tuple(sorted([symbol, pos.symbol]))
            corr = self._correlation_matrix.get(pair, 0.25)
            if corr > 0.80:
                return False, f"Risk concentration: {symbol} has extreme positive correlation ({corr}) with active position {pos.symbol}."
        return True, "No correlation breaches found."

class DrawdownAgent:
    """
    Drawdown monitoring agent. Blocks new buy Orders if overall loss limits are triggered.
    """
    def __init__(self, max_drawdown: float = 0.15):
        self.max_drawdown = max_drawdown

    def check_drawdown(self, portfolio_peak_valuation: float, current_valuation: float) -> tuple[bool, str]:
        if portfolio_peak_valuation == 0:
            return True, "No peak history recorded"
            
        drawdown_pct = (portfolio_peak_valuation - current_valuation) / portfolio_peak_valuation
        if drawdown_pct > self.max_drawdown:
            return False, f"Critical System Drawdown: Active drawdown of {drawdown_pct*100:.1f}% exceeds total risk limit {self.max_drawdown*100:.1f}%. All buying freeze active."
        return True, "Drawdown parameters safe."

class FinalRiskVetoAgent:
    """
    Absolute coordination node for risk controls.
    Can veto any order generated by trading consensus.
    Logs RiskEvents on failures.
    """
    def __init__(self, default_trade_size: float = 100.0):
        self.sizer = PositionSizingAgent(default_size=default_trade_size)
        self.exposure = ExposureAgent(max_sector_limit=settings.MAX_SECTOR_EXPOSURE)
        self.correlation = CorrelationAgent()
        self.drawdown_checker = DrawdownAgent(max_drawdown=settings.MAX_TOTAL_DRAWDOWN)
        self.veto_history: List[RiskEvent] = []

    def vet_proposed_order(
        self,
        symbol: str,
        side: OrderSide,
        confidence: float,
        sector: str,
        active_cash: float,
        active_positions: List[Position],
        total_portfolio_equity: float,
        peak_portfolio_equity: float
    ) -> tuple[bool, Optional[Trade], str]:
        """
        Coordinates all child risk systems. Returns (cleared_boolean, optional_fitted_trade_or_none, explanation)
        """
        if side != OrderSide.BUY:
            # Sells and Holds bypass core risk limits to support defensive liquidation
            dummy_trade = Trade(
                id=f"tr_{uuid.uuid4().hex[:8]}",
                symbol=symbol,
                side=side,
                order_type=OrderType.MARKET,
                quantity=0.0,
                price=0.0,
                total_amount=0.0,
                status=TradeStatus.PENDING,
                agent_id_source="risk_bypass",
                thesis_summary=f"Defensive exit action verified by risk rules."
            )
            return True, dummy_trade, "Sell/Hold action approved without risk restriction."

        # 1. Check Drawdown freeze
        cleared, msg = self.drawdown_checker.check_drawdown(peak_portfolio_equity, total_portfolio_equity)
        if not cleared:
            self._log_veto(symbol, "drawdown_agent", msg, {"p_peak": peak_portfolio_equity, "p_equity": total_portfolio_equity})
            return False, None, msg

        # 2. Check position caps
        if len(active_positions) >= settings.MAX_POSITION_COUNT:
            err = f"Max position count reached ({settings.MAX_POSITION_COUNT}). Order vetoed."
            self._log_veto(symbol, "count_agent", err, {"pos_count": len(active_positions)})
            return False, None, err

        # 3. Position Sizing
        fitted_size = self.sizer.calculate_size(confidence, symbol, active_cash)
        if fitted_size == 0.0:
            err = "Candidate trade amount resolves to 0 due to cash depletion."
            return False, None, err

        # 4. Exposure
        cleared, msg = self.exposure.valuate_exposure_limit(symbol, sector, fitted_size, active_positions, total_portfolio_equity)
        if not cleared:
            self._log_veto(symbol, "exposure_agent", msg, {"allocated_amount": fitted_size})
            return False, None, msg

        # 5. Correlation
        cleared, msg = self.correlation.check_correlation(symbol, active_positions)
        if not cleared:
            self._log_veto(symbol, "correlation_agent", msg, {"positions": [p.symbol for p in active_positions]})
            return False, None, msg

        # Order Cleared! Setup finished trade structure
        final_trade = Trade(
            id=f"tr_{uuid.uuid4().hex[:8]}",
            symbol=symbol,
            side=OrderSide.BUY,
            order_type=OrderType.MARKET,
            quantity=0.0,  # Will be calculated at current price at runtime execution
            price=0.0,
            total_amount=fitted_size,
            status=TradeStatus.PENDING,
            agent_id_source="final_risk_veto",
            thesis_summary="Trade cleared risk and approved for execution."
        )
        return True, final_trade, "Risk cleared. Order passed through for broker fill."

    def _log_veto(self, symbol: str, agent: str, reason: str, metadata: Dict[str, Any]):
        veto_event = RiskEvent(
            id=f"rt_{uuid.uuid4().hex[:8]}",
            symbol=symbol,
            target_trade_id="pending_" + symbol,
            vetoed_by=agent,
            veto_reason=reason,
            original_trade_details={"symbol": symbol, "conf": float(settings.DEFAULT_TRADE_SIZE)},
            action_taken="FULL_VETO"
        )
        self.veto_history.append(veto_event)
