import type { AppTabId, NavDomain } from './responsiveNavConfig';
import type { MobileTabId } from '../mobile/mobileTabs';

export type NavTooltipCopy = {
  title: string;
  purpose: string;
};

/** Viewport-safe horizontal center for a `-translate-x-1/2` tooltip. */
export function clampCenteredTooltipLeft(
  anchorX: number,
  tooltipWidth: number,
  viewportWidth: number,
  pad = 12,
): number {
  const half = Math.max(tooltipWidth, 1) / 2;
  const minCenter = pad + half;
  const maxCenter = viewportWidth - pad - half;
  if (!Number.isFinite(anchorX) || !Number.isFinite(viewportWidth) || viewportWidth <= 0) {
    return 0;
  }
  if (maxCenter <= minCenter) return viewportWidth / 2;
  return Math.min(maxCenter, Math.max(minCenter, anchorX));
}

export const NAV_TAB_TOOLTIPS: Record<AppTabId, NavTooltipCopy> = {
  dashboard: {
    title: 'Autonomous Dashboard',
    purpose:
      'Executive overview of total account equity, intraday P&L trajectories, active holdings valuation, and high-level agent consensus status.',
  },
  command: {
    title: 'Mission Control',
    purpose:
      'Central command desk for Autobot toggles, emergency kill switches, individual agent pipeline enable/disable switches, and broker execution modes.',
  },
  portfolio: {
    title: 'Holdings & Positions',
    purpose:
      'Real-time ledger of active asset holdings, unrealized and realized P&L, entry prices, and portfolio scenario stress-testing simulators.',
  },
  arena: {
    title: 'Trading Arena',
    purpose:
      'Intraday execution cockpit featuring real-time market sentiment trends, asset trade analytics, and manual paper order controls.',
  },
  news: {
    title: 'News Intel',
    purpose:
      'Real-time global market headline feed with automated FinBERT sentiment classification, event clustering, and provider reliability metrics.',
  },
  opportunities: {
    title: 'Opportunity Feed',
    purpose:
      'Real-time stream of high-confidence BUY/SELL trade proposals generated by active scanning agents. A listed idea is not a Chief-approved order.',
  },
  premarket: {
    title: 'Premarket Intelligence',
    purpose:
      'Session state, today\'s real TradePlan hypotheses, the latest candidate ranking, and missed-opportunity diagnostics. Read-only — no TradePlan currently reaches the live trade-idea pipeline.',
  },
  scanner: {
    title: 'Strategy Scanner',
    purpose:
      'Technical indicator scanner screening watchlists for RSI extremes, MACD momentum crosses, and Bollinger Band breakouts.',
  },
  agents: {
    title: 'Agent Network',
    purpose:
      'Live visual EventBus telemetry graph illustrating real-time WebSocket packet flows, model inference pulses, and agent consensus routing.',
  },
  evaluation: {
    title: 'Agent Evaluation',
    purpose:
      'Performance leaderboard tracking individual agent prediction accuracy, win rates, latencies, and dynamic consensus weights.',
  },
  kronos: {
    title: 'Kronos Model',
    purpose:
      'Deep-learning time-series forecasting service displaying model inference benchmarks, directional accuracy, and forecast horizons.',
  },
  learning: {
    title: 'Learning & Evolution',
    purpose:
      'Post-trade reflection engine and adaptive memory rule extraction derived from historical trade outcomes.',
  },
  memory: {
    title: 'Vec Event Memory',
    purpose:
      'Semantic vector memory explorer for querying historical market contexts and similar past trade setups. Event-memory HTTP routes are quarantined (410) — research only, not an order path.',
  },
  observatory: {
    title: 'Observatory',
    purpose:
      'Full decision and transaction explorer for inspecting complete lifecycle event traces by unique traceId.',
  },
  activity: {
    title: 'Activity Log',
    purpose:
      'Chronological audit trail streaming EventBus messages, risk evaluations, order submissions, and system warnings for this process.',
  },
  diagnostics: {
    title: 'Diagnostics',
    purpose:
      'Infrastructure health monitor displaying process memory usage, database WAL state, broker WebSocket heartbeats, and API latencies.',
  },
  audit: {
    title: 'Observability & Tracing',
    purpose:
      'Comprehensive 7-table decision reconstructor verifying deterministic trace consistency and risk gate evaluations.',
  },
  validation: {
    title: 'Validation',
    purpose:
      'Quantitative validation suite displaying walk-forward optimization metrics, live readiness scorecards, and gating criteria. Green widgets are not LIVE authorization.',
  },
  settings: {
    title: 'Settings & Keys',
    purpose:
      'Configuration manager for broker API credentials, local/remote AI model routing, risk guardrail limits, and UI preferences.',
  },
  documentation: {
    title: 'Documentation',
    purpose:
      'Built-in platform architecture manual, 25-gate risk formulas, and operational production runbooks. Not an order surface.',
  },
};

export const NAV_DOMAIN_TOOLTIPS: Record<NavDomain | 'more', NavTooltipCopy> = {
  trade: {
    title: 'Trade',
    purpose: 'Operate the book: Autonomous Dashboard, Mission Control, Holdings & Positions, and Trading Arena.',
  },
  agents: {
    title: 'Agents',
    purpose: 'Agent Network, Evaluation, Vec Event Memory, Activity Log, and Observatory desks.',
  },
  quant: {
    title: 'Quant',
    purpose: 'Strategy Scanner, Intelligence, Learning & Evolution, Kronos Model, Opportunity Feed, and Premarket Intelligence.',
  },
  system: {
    title: 'System',
    purpose: 'News Intel, Settings & Keys, Diagnostics, Observability & Tracing, Validation, and Documentation.',
  },
  more: {
    title: 'All desks',
    purpose: 'Open the full tab list. Hover any desk for its purpose, function, and data scope.',
  },
};

export const MOBILE_TAB_TOOLTIPS: Record<MobileTabId, NavTooltipCopy> = {
  cockpit: {
    title: 'Cockpit',
    purpose: 'Phone mission home: equity, session P&L, Autobot state, and high-level consensus status.',
  },
  positions: {
    title: 'Positions',
    purpose: 'Open holdings ledger with live marks, entry prices, and unrealized P&L.',
  },
  brain: {
    title: 'AI Brain',
    purpose: 'Agent network and consensus view sized for a phone — EventBus routing, not a second order path.',
  },
  risk: {
    title: 'Risk',
    purpose: 'Risk-gate monitor, halt state, and Argus allocation versus broker capital.',
  },
  terminal: {
    title: 'Terminal',
    purpose: 'Operator logs, diagnostics heartbeats, and process health on a compact surface.',
  },
  settings: {
    title: 'Settings',
    purpose: 'Touch-first dual-config overlays, paper-locked broker selection, and secret-safe credential status. Does not arm LIVE.',
  },
};
