package io.argus.quantcore.features;

import io.argus.quantcore.backtest.engine.Bar;
import io.argus.quantcore.server.json.Json;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

/**
 * Parity against the real RegimeEngine.ts / MarketContext.ts / indicators/{trend,volatility,
 * priceAction,volume,supportResistance}.ts (JMIG-001), run on identical synthetic Bar fixtures
 * generated by scripts/java_parity_fixtures_phase2.ts (ground truth captured 2026-09-04). Fixture
 * source: quant-core-java/src/test/resources/parity/phase2_fixtures.json.
 *
 * Tolerance: 1e-6 absolute for raw ported arithmetic. Both languages use IEEE 754 double and the
 * same operation order was deliberately preserved function-by-function during porting (same
 * summation order, same Wilder-smoothing iteration, same slice boundaries) - results should be
 * effectively exact. 1e-6 absorbs only benign floating-point summation-order noise across a ~250-
 * iteration Wilder smoothing pass, not a real algorithmic divergence; a mismatch beyond this
 * tolerance means the port has a real bug, not float noise.
 */
class Phase2FeatureParityTest {
    private static final double EPS = 1e-6;
    private static Map<String, Object> root;

    @BeforeAll
    static void loadFixtures() throws IOException {
        Path path = Path.of("src/test/resources/parity/phase2_fixtures.json");
        String json = Files.readString(path);
        root = Json.asObject(Json.parse(json));
    }

    // ---------- JSON plumbing helpers ----------

    private static Map<String, Object> fixture(String name) {
        return Json.asObject(Json.asObject(root.get("fixtures")).get(name));
    }

    private static Map<String, Object> marketContextScenario(String name) {
        return Json.asObject(Json.asObject(root.get("marketContext")).get(name));
    }

    @SuppressWarnings("unchecked")
    private static List<Bar> readBars(Object rawBarsList) {
        List<Object> rawBars = (List<Object>) rawBarsList;
        List<Bar> out = new ArrayList<>();
        for (Object o : rawBars) {
            Map<String, Object> b = Json.asObject(o);
            out.add(new Bar(
                Json.asDouble(b.get("timestamp")).longValue(),
                Json.asDoublePrimitive(b.get("open"), 0),
                Json.asDoublePrimitive(b.get("high"), 0),
                Json.asDoublePrimitive(b.get("low"), 0),
                Json.asDoublePrimitive(b.get("close"), 0),
                Json.asDoublePrimitive(b.get("volume"), 0)
            ));
        }
        return out;
    }

    private static List<Bar> bars(Map<String, Object> fixture) {
        return readBars(fixture.get("bars"));
    }

    private static Double d(Map<String, Object> obj, String key) {
        return obj == null ? null : Json.asDouble(obj.get(key));
    }

    private static String s(Map<String, Object> obj, String key) {
        return obj == null ? null : Json.asString(obj.get(key));
    }

    private static Boolean bo(Map<String, Object> obj, String key) {
        return obj == null ? null : Json.asBoolean(obj.get(key));
    }

    private static Map<String, Object> m(Map<String, Object> obj, String key) {
        Object v = obj == null ? null : obj.get(key);
        return v == null ? null : Json.asObject(v);
    }

    private static void assertClose(String msg, Double expected, Double actual) {
        if (expected == null) {
            assertThat(actual).as(msg + " (expected null)").isNull();
            return;
        }
        assertThat(actual).as(msg + " (expected non-null)").isNotNull();
        assertThat(actual).as(msg).isCloseTo(expected, within(EPS));
    }

    // ---------- TrendFeatures.Result parity ----------

    private static void assertTrend(String label, Map<String, Object> expected, TrendFeatures.Result actual) {
        Map<String, Object> ma = m(expected, "movingAverages");
        assertClose(label + ".ma.sma20", d(ma, "sma20"), actual.movingAverages().sma20());
        assertClose(label + ".ma.sma50", d(ma, "sma50"), actual.movingAverages().sma50());
        assertClose(label + ".ma.sma100", d(ma, "sma100"), actual.movingAverages().sma100());
        assertClose(label + ".ma.sma200", d(ma, "sma200"), actual.movingAverages().sma200());
        assertClose(label + ".ma.ema9", d(ma, "ema9"), actual.movingAverages().ema9());
        assertClose(label + ".ma.ema20", d(ma, "ema20"), actual.movingAverages().ema20());
        assertClose(label + ".ma.ema50", d(ma, "ema50"), actual.movingAverages().ema50());
        assertClose(label + ".ma.ema200", d(ma, "ema200"), actual.movingAverages().ema200());

        assertPriceVsMa(label + ".priceVsSMA20", m(expected, "priceVsSMA20"), actual.priceVsSMA20());
        assertPriceVsMa(label + ".priceVsSMA50", m(expected, "priceVsSMA50"), actual.priceVsSMA50());
        assertPriceVsMa(label + ".priceVsSMA200", m(expected, "priceVsSMA200"), actual.priceVsSMA200());

        assertClose(label + ".sma50SlopePct", d(expected, "sma50SlopePct"), actual.sma50SlopePct());

        Map<String, Object> dmi = m(expected, "dmi");
        if (dmi == null) {
            assertThat(actual.dmi()).as(label + ".dmi (expected null)").isNull();
        } else {
            assertThat(actual.dmi()).as(label + ".dmi (expected non-null)").isNotNull();
            assertClose(label + ".dmi.plusDI", d(dmi, "plusDI"), actual.dmi().plusDI());
            assertClose(label + ".dmi.minusDI", d(dmi, "minusDI"), actual.dmi().minusDI());
            assertClose(label + ".dmi.adx", d(dmi, "adx"), actual.dmi().adx());
        }

        Map<String, Object> structure = m(expected, "structure");
        assertThat(actual.structure().trend()).as(label + ".structure.trend").isEqualTo(s(structure, "trend"));
        assertThat(actual.structure().event()).as(label + ".structure.event").isEqualTo(s(structure, "event"));
        assertClose(label + ".structure.lastSwingHigh", d(structure, "lastSwingHigh"), actual.structure().lastSwingHigh());
        assertClose(label + ".structure.lastSwingLow", d(structure, "lastSwingLow"), actual.structure().lastSwingLow());
    }

    private static void assertPriceVsMa(String label, Map<String, Object> expected, TrendFeatures.PriceVsMA actual) {
        if (expected == null) {
            assertThat(actual).as(label + " (expected null)").isNull();
            return;
        }
        assertThat(actual).as(label + " (expected non-null)").isNotNull();
        assertClose(label + ".diff", d(expected, "diff"), actual.diff());
        assertClose(label + ".diffPct", d(expected, "diffPct"), actual.diffPct());
        assertThat(actual.above()).as(label + ".above").isEqualTo(bo(expected, "above"));
    }

    // ---------- VolatilityFeatures.Result parity ----------

    private static void assertVolatility(String label, Map<String, Object> expected, VolatilityFeatures.Result actual) {
        assertClose(label + ".atr", d(expected, "atr"), actual.atr());
        assertClose(label + ".atrPercent", d(expected, "atrPercent"), actual.atrPercent());
        assertClose(label + ".historicalVolatilityPct", d(expected, "historicalVolatilityPct"), actual.historicalVolatilityPct());
        assertClose(label + ".volatilityPercentile", d(expected, "volatilityPercentile"), actual.volatilityPercentile());
        assertClose(label + ".bollingerBandWidthPct", d(expected, "bollingerBandWidthPct"), actual.bollingerBandWidthPct());

        Map<String, Object> keltner = m(expected, "keltner");
        if (keltner == null) {
            assertThat(actual.keltner()).as(label + ".keltner (expected null)").isNull();
        } else {
            assertThat(actual.keltner()).as(label + ".keltner (expected non-null)").isNotNull();
            assertClose(label + ".keltner.middle", d(keltner, "middle"), actual.keltner().middle());
            assertClose(label + ".keltner.upper", d(keltner, "upper"), actual.keltner().upper());
            assertClose(label + ".keltner.lower", d(keltner, "lower"), actual.keltner().lower());
        }

        assertThat(actual.regime()).as(label + ".regime").isEqualTo(s(expected, "regime"));
        assertClose(label + ".closePriceZScore", d(expected, "closePriceZScore"), actual.closePriceZScore());
    }

    // ---------- PriceActionFeatures.Result parity ----------

    private static void assertPriceAction(String label, Map<String, Object> expected, PriceActionFeatures.Result actual) {
        Map<String, Object> gap = m(expected, "gap");
        assertThat(actual.gap().type()).as(label + ".gap.type").isEqualTo(s(gap, "type"));
        assertClose(label + ".gap.sizePct", d(gap, "sizePct"), actual.gap().sizePct());

        assertThat(actual.consolidating()).as(label + ".consolidating").isEqualTo(bo(expected, "consolidating"));
        assertThat(actual.rangeRegime()).as(label + ".rangeRegime").isEqualTo(s(expected, "rangeRegime"));
        assertThat(actual.candlestick()).as(label + ".candlestick").isEqualTo(s(expected, "candlestick"));
    }

    // ---------- VolumeFeatures.Result parity ----------

    private static void assertVolume(String label, Map<String, Object> expected, VolumeFeatures.Result actual) {
        assertClose(label + ".volumeSMA20", d(expected, "volumeSMA20"), actual.volumeSMA20());
        assertClose(label + ".relativeVolume", d(expected, "relativeVolume"), actual.relativeVolume());
        assertThat(actual.isSpike()).as(label + ".isSpike").isEqualTo(bo(expected, "isSpike"));
        assertClose(label + ".volumeROC", d(expected, "volumeROC"), actual.volumeROC());
        assertClose(label + ".obv", d(expected, "obv"), actual.obv());
        assertClose(label + ".mfi", d(expected, "mfi"), actual.mfi());

        Map<String, Object> vwap = m(expected, "vwap");
        assertClose(label + ".vwap.vwap", d(vwap, "vwap"), actual.vwap().vwap());
        assertClose(label + ".vwap.distancePct", d(vwap, "distancePct"), actual.vwap().distancePct());
        assertClose(label + ".vwap.slopePct", d(vwap, "slopePct"), actual.vwap().slopePct());
        assertThat(actual.vwap().event()).as(label + ".vwap.event").isEqualTo(s(vwap, "event"));

        assertClose(label + ".cmf", d(expected, "cmf"), actual.cmf());
        assertClose(label + ".ad", d(expected, "ad"), actual.ad());
    }

    // ---------- SupportResistanceFeatures.Result parity ----------

    private static void assertOhlc(String label, Map<String, Object> expected, SupportResistanceFeatures.Ohlc actual) {
        if (expected == null) {
            assertThat(actual).as(label + " (expected null)").isNull();
            return;
        }
        assertThat(actual).as(label + " (expected non-null)").isNotNull();
        assertClose(label + ".high", d(expected, "high"), actual.high());
        assertClose(label + ".low", d(expected, "low"), actual.low());
        assertClose(label + ".close", d(expected, "close"), actual.close());
    }

    private static void assertSupportResistance(String label, Map<String, Object> expected, SupportResistanceFeatures.Result actual) {
        assertOhlc(label + ".previousDay", m(expected, "previousDay"), actual.previousDay());
        assertOhlc(label + ".dailyHighLow", m(expected, "dailyHighLow"), actual.dailyHighLow());
        assertOhlc(label + ".weeklyHighLow", m(expected, "weeklyHighLow"), actual.weeklyHighLow());
        assertOhlc(label + ".priorChannel20", m(expected, "priorChannel20"), actual.priorChannel20());

        Map<String, Object> pivots = m(expected, "pivots");
        if (pivots == null) {
            assertThat(actual.pivots()).as(label + ".pivots (expected null)").isNull();
        } else {
            assertClose(label + ".pivots.pivot", d(pivots, "pivot"), actual.pivots().pivot());
            assertClose(label + ".pivots.r1", d(pivots, "r1"), actual.pivots().r1());
            assertClose(label + ".pivots.r2", d(pivots, "r2"), actual.pivots().r2());
            assertClose(label + ".pivots.r3", d(pivots, "r3"), actual.pivots().r3());
            assertClose(label + ".pivots.s1", d(pivots, "s1"), actual.pivots().s1());
            assertClose(label + ".pivots.s2", d(pivots, "s2"), actual.pivots().s2());
            assertClose(label + ".pivots.s3", d(pivots, "s3"), actual.pivots().s3());
        }

        Map<String, Object> fib = m(expected, "fibonacci");
        if (fib == null) {
            assertThat(actual.fibonacci()).as(label + ".fibonacci (expected null)").isNull();
        } else {
            assertClose(label + ".fib.level0", d(fib, "level0"), actual.fibonacci().level0());
            assertClose(label + ".fib.level236", d(fib, "level236"), actual.fibonacci().level236());
            assertClose(label + ".fib.level382", d(fib, "level382"), actual.fibonacci().level382());
            assertClose(label + ".fib.level500", d(fib, "level500"), actual.fibonacci().level500());
            assertClose(label + ".fib.level618", d(fib, "level618"), actual.fibonacci().level618());
            assertClose(label + ".fib.level786", d(fib, "level786"), actual.fibonacci().level786());
            assertClose(label + ".fib.level100", d(fib, "level100"), actual.fibonacci().level100());
        }

        assertThat(actual.recentSwings()).as(label + ".recentSwings.size").hasSize(((List<?>) expected.get("recentSwings")).size());

        Map<String, Object> nearest = m(expected, "nearest");
        assertLevelDistance(label + ".nearest.nearestResistance", m(nearest, "nearestResistance"), actual.nearest().nearestResistance());
        assertLevelDistance(label + ".nearest.nearestSupport", m(nearest, "nearestSupport"), actual.nearest().nearestSupport());

        Map<String, Object> or = m(expected, "openingRange");
        Map<String, Object> orData = m(or, "data");
        assertThat(actual.openingRange().available()).as(label + ".openingRange.available").isEqualTo(bo(or, "available"));
        SupportResistanceFeatures.Range actualOrData = actual.openingRange().data();
        assertClose(label + ".openingRange.data.high", d(orData, "high"), actualOrData == null ? null : actualOrData.high());
        assertClose(label + ".openingRange.data.low", d(orData, "low"), actualOrData == null ? null : actualOrData.low());
    }

    private static void assertLevelDistance(String label, Map<String, Object> expected, SupportResistanceFeatures.LevelDistance actual) {
        if (expected == null) {
            assertThat(actual).as(label + " (expected null)").isNull();
            return;
        }
        assertThat(actual).as(label + " (expected non-null)").isNotNull();
        assertClose(label + ".level", d(expected, "level"), actual.level());
        assertClose(label + ".abs", d(expected, "abs"), actual.abs());
        assertClose(label + ".pct", d(expected, "pct"), actual.pct());
    }

    // ---------- RegimeEngine.Result parity ----------

    private static void assertRegime(String label, Map<String, Object> expected, RegimeEngine.Result actual) {
        assertThat(actual.regime()).as(label + ".regime").isEqualTo(s(expected, "regime"));
        assertClose(label + ".trendStrength", d(expected, "trendStrength"), actual.trendStrength());
        assertThat(actual.volatility()).as(label + ".volatility").isEqualTo(s(expected, "volatility"));
        assertThat(actual.marketStructure()).as(label + ".marketStructure").isEqualTo(s(expected, "marketStructure"));
        assertClose(label + ".confidence", d(expected, "confidence"), actual.confidence());
        assertThat(actual.insufficientData()).as(label + ".insufficientData").isEqualTo(bo(expected, "insufficientData"));

        Map<String, Object> features = m(expected, "features");
        assertTrend(label + ".features.trend", m(features, "trend"), actual.trend());
        assertVolatility(label + ".features.volatility", m(features, "volatility"), actual.volatilityFeatures());
        assertPriceAction(label + ".features.priceAction", m(features, "priceAction"), actual.priceAction());
    }

    // ---------- Per-fixture tests ----------

    @Test
    void insufficientDataMatchesTypeScript() {
        Map<String, Object> fx = fixture("insufficientData");
        List<Bar> bars = bars(fx);

        assertTrend("insufficientData.trend", m(fx, "trend"), TrendFeatures.computeTrendFeatures(bars));
        assertVolatility("insufficientData.volatility", m(fx, "volatility"), VolatilityFeatures.computeVolatilityFeatures(bars));
        assertPriceAction("insufficientData.priceAction", m(fx, "priceAction"), PriceActionFeatures.computePriceActionFeatures(bars));
        assertVolume("insufficientData.volume", m(fx, "volume"), VolumeFeatures.computeVolumeFeatures(bars));
        assertSupportResistance("insufficientData.supportResistance", m(fx, "supportResistance"), SupportResistanceFeatures.computeSupportResistanceFeatures(bars));
        assertRegime("insufficientData.regime", m(fx, "regime"), RegimeEngine.classifyRegime(bars));
    }

    @Test
    void uptrend120MatchesTypeScript() {
        Map<String, Object> fx = fixture("uptrend120");
        List<Bar> bars = bars(fx);

        assertTrend("uptrend120.trend", m(fx, "trend"), TrendFeatures.computeTrendFeatures(bars));
        assertVolatility("uptrend120.volatility", m(fx, "volatility"), VolatilityFeatures.computeVolatilityFeatures(bars));
        assertPriceAction("uptrend120.priceAction", m(fx, "priceAction"), PriceActionFeatures.computePriceActionFeatures(bars));
        assertVolume("uptrend120.volume", m(fx, "volume"), VolumeFeatures.computeVolumeFeatures(bars));
        assertSupportResistance("uptrend120.supportResistance", m(fx, "supportResistance"), SupportResistanceFeatures.computeSupportResistanceFeatures(bars));
        assertRegime("uptrend120.regime", m(fx, "regime"), RegimeEngine.classifyRegime(bars));

        SupportResistanceFeatures.AvailableRange premarket = SupportResistanceFeatures.premarketHighLow(bars, bars.get(30).timestampMs());
        Map<String, Object> expectedPremarket = m(fx, "premarketHighLow");
        assertThat(premarket.available()).as("uptrend120.premarketHighLow.available").isEqualTo(bo(expectedPremarket, "available"));
    }

    @Test
    void downtrend120MatchesTypeScript() {
        Map<String, Object> fx = fixture("downtrend120");
        List<Bar> bars = bars(fx);

        assertTrend("downtrend120.trend", m(fx, "trend"), TrendFeatures.computeTrendFeatures(bars));
        assertVolatility("downtrend120.volatility", m(fx, "volatility"), VolatilityFeatures.computeVolatilityFeatures(bars));
        assertPriceAction("downtrend120.priceAction", m(fx, "priceAction"), PriceActionFeatures.computePriceActionFeatures(bars));
        assertVolume("downtrend120.volume", m(fx, "volume"), VolumeFeatures.computeVolumeFeatures(bars));
        assertSupportResistance("downtrend120.supportResistance", m(fx, "supportResistance"), SupportResistanceFeatures.computeSupportResistanceFeatures(bars));
        assertRegime("downtrend120.regime", m(fx, "regime"), RegimeEngine.classifyRegime(bars));
    }

    @Test
    void rangingChoppy80MatchesTypeScript() {
        Map<String, Object> fx = fixture("rangingChoppy80");
        List<Bar> bars = bars(fx);

        assertTrend("rangingChoppy80.trend", m(fx, "trend"), TrendFeatures.computeTrendFeatures(bars));
        assertVolatility("rangingChoppy80.volatility", m(fx, "volatility"), VolatilityFeatures.computeVolatilityFeatures(bars));
        assertPriceAction("rangingChoppy80.priceAction", m(fx, "priceAction"), PriceActionFeatures.computePriceActionFeatures(bars));
        assertVolume("rangingChoppy80.volume", m(fx, "volume"), VolumeFeatures.computeVolumeFeatures(bars));
        assertSupportResistance("rangingChoppy80.supportResistance", m(fx, "supportResistance"), SupportResistanceFeatures.computeSupportResistanceFeatures(bars));
        assertRegime("rangingChoppy80.regime", m(fx, "regime"), RegimeEngine.classifyRegime(bars));
    }

    @Test
    void longRich280MatchesTypeScript_gapVolumeSpikeEngulfingBullishTrend() {
        Map<String, Object> fx = fixture("longRich280");
        List<Bar> bars = bars(fx);

        assertTrend("longRich280.trend", m(fx, "trend"), TrendFeatures.computeTrendFeatures(bars));
        assertVolatility("longRich280.volatility", m(fx, "volatility"), VolatilityFeatures.computeVolatilityFeatures(bars));
        assertPriceAction("longRich280.priceAction", m(fx, "priceAction"), PriceActionFeatures.computePriceActionFeatures(bars));
        assertVolume("longRich280.volume", m(fx, "volume"), VolumeFeatures.computeVolumeFeatures(bars));
        assertSupportResistance("longRich280.supportResistance", m(fx, "supportResistance"), SupportResistanceFeatures.computeSupportResistanceFeatures(bars));
        assertRegime("longRich280.regime", m(fx, "regime"), RegimeEngine.classifyRegime(bars));

        // Sanity-check the engineered tail event landed on both sides identically (belt-and-braces
        // on top of the field-by-field asserts above).
        PriceActionFeatures.Result pa = PriceActionFeatures.computePriceActionFeatures(bars);
        assertThat(pa.gap().type()).isEqualTo("GAP_UP");
        assertThat(pa.candlestick()).isEqualTo("BEARISH_ENGULFING");
        assertThat(VolumeFeatures.computeVolumeFeatures(bars).isSpike()).isTrue();
    }

    @Test
    void intradayOpeningRangeMatchesTypeScript() {
        Map<String, Object> fx = fixture("intradayOpeningRange");
        List<Bar> bars = bars(fx);

        assertTrend("intradayOpeningRange.trend", m(fx, "trend"), TrendFeatures.computeTrendFeatures(bars));
        assertVolatility("intradayOpeningRange.volatility", m(fx, "volatility"), VolatilityFeatures.computeVolatilityFeatures(bars));
        assertPriceAction("intradayOpeningRange.priceAction", m(fx, "priceAction"), PriceActionFeatures.computePriceActionFeatures(bars));
        assertVolume("intradayOpeningRange.volume", m(fx, "volume"), VolumeFeatures.computeVolumeFeatures(bars));
        assertSupportResistance("intradayOpeningRange.supportResistance", m(fx, "supportResistance"), SupportResistanceFeatures.computeSupportResistanceFeatures(bars));
        assertRegime("intradayOpeningRange.regime", m(fx, "regime"), RegimeEngine.classifyRegime(bars));

        // This is the one fixture with real intraday (5-minute) spacing - openingRange must be
        // AVAILABLE here (every daily-granularity fixture above correctly reports unavailable).
        assertThat(SupportResistanceFeatures.computeSupportResistanceFeatures(bars).openingRange().available()).isTrue();

        Map<String, Object> expectedPremarket = m(fx, "premarketHighLow");
        Map<String, Object> expectedPremarketData = m(expectedPremarket, "data");
        long premarketWindowMs = bars.get(0).timestampMs() + 30 * 60_000L;
        SupportResistanceFeatures.AvailableRange premarket = SupportResistanceFeatures.premarketHighLow(bars, premarketWindowMs);
        assertThat(premarket.available()).as("intradayOpeningRange.premarketHighLow.available").isEqualTo(bo(expectedPremarket, "available"));
        SupportResistanceFeatures.Range premarketData = premarket.data();
        assertClose("intradayOpeningRange.premarketHighLow.data.high", d(expectedPremarketData, "high"), premarketData == null ? null : premarketData.high());
        assertClose("intradayOpeningRange.premarketHighLow.data.low", d(expectedPremarketData, "low"), premarketData == null ? null : premarketData.low());
    }

    // ---------- MarketContext (pure-core) parity ----------

    private static void assertRelativeStrength(String label, Map<String, Object> expected, MarketContext.RelativeStrength actual) {
        if (expected == null) {
            assertThat(actual).as(label + " (expected null)").isNull();
            return;
        }
        assertThat(actual).as(label + " (expected non-null)").isNotNull();
        assertThat(actual.vsSymbol()).as(label + ".vsSymbol").isEqualTo(s(expected, "vsSymbol"));
        assertClose(label + ".periodPct", d(expected, "periodPct"), actual.periodPct());
        assertClose(label + ".benchmarkPeriodPct", d(expected, "benchmarkPeriodPct"), actual.benchmarkPeriodPct());
        assertClose(label + ".relativeStrengthPct", d(expected, "relativeStrengthPct"), actual.relativeStrengthPct());
        assertClose(label + ".correlation", d(expected, "correlation"), actual.correlation());
        assertClose(label + ".beta", d(expected, "beta"), actual.beta());
    }

    private static void assertBenchmarkTrend(String label, Map<String, Object> expected, MarketContext.BenchmarkTrend actual) {
        assertThat(actual.symbol()).as(label + ".symbol").isEqualTo(s(expected, "symbol"));
        Map<String, Object> regime = m(expected, "regime");
        if (regime == null) {
            assertThat(actual.regime()).as(label + ".regime (expected null)").isNull();
        } else {
            assertRegime(label + ".regime", regime, actual.regime());
        }
    }

    @Test
    void marketContextAaplVsBenchmarksMatchesTypeScript() {
        Map<String, Object> scenario = marketContextScenario("aaplVsBenchmarks");
        List<Bar> symbolBars = readBars(scenario.get("symbolBars"));
        Map<String, Object> benchmarkBars = m(scenario, "benchmarkBars");
        List<Bar> spyBars = readBars(benchmarkBars.get("SPY"));
        List<Bar> qqqBars = readBars(benchmarkBars.get("QQQ"));
        List<Bar> iwmBars = readBars(benchmarkBars.get("IWM"));
        List<Bar> xlkBars = readBars(benchmarkBars.get("XLK"));

        MarketContext.Result actual = MarketContext.getMarketContext(symbolBars, "1Day",
            MarketContext.BenchmarkInput.ok(spyBars),
            MarketContext.BenchmarkInput.ok(qqqBars),
            MarketContext.BenchmarkInput.ok(iwmBars),
            "Technology", "XLK", MarketContext.BenchmarkInput.ok(xlkBars));

        Map<String, Object> expected = m(scenario, "result");
        assertBenchmarkTrend("aaplVsBenchmarks.spy", m(expected, "spy"), actual.spy());
        assertBenchmarkTrend("aaplVsBenchmarks.qqq", m(expected, "qqq"), actual.qqq());
        assertBenchmarkTrend("aaplVsBenchmarks.iwm", m(expected, "iwm"), actual.iwm());

        Map<String, Object> sector = m(expected, "sector");
        assertThat(actual.sector().name()).isEqualTo(s(sector, "name"));
        assertThat(actual.sector().etf()).isEqualTo(s(sector, "etf"));
        assertBenchmarkTrend("aaplVsBenchmarks.sector.trend", m(sector, "trend"), actual.sector().trend());

        assertRelativeStrength("aaplVsBenchmarks.relativeStrengthVsSPY", m(expected, "relativeStrengthVsSPY"), actual.relativeStrengthVsSPY());
        assertRelativeStrength("aaplVsBenchmarks.relativeStrengthVsSector", m(expected, "relativeStrengthVsSector"), actual.relativeStrengthVsSector());

        Map<String, Object> breadth = m(expected, "breadth");
        assertThat(actual.breadth().available()).isEqualTo(bo(breadth, "available"));
    }

    @Test
    void marketContextUnknownSectorMatchesTypeScript() {
        Map<String, Object> scenario = marketContextScenario("unknownSector");
        List<Bar> symbolBars = readBars(scenario.get("symbolBars"));
        Map<String, Object> benchmarkBars = m(scenario, "benchmarkBars");
        List<Bar> spyBars = readBars(benchmarkBars.get("SPY"));
        List<Bar> qqqBars = readBars(benchmarkBars.get("QQQ"));
        List<Bar> iwmBars = readBars(benchmarkBars.get("IWM"));

        // ZZZZ_UNMAPPED is not in PositionSizing.SECTOR_MAP - sectorName/sectorEtf are null,
        // exactly as the real getSector('ZZZZ_UNMAPPED') would resolve.
        MarketContext.Result actual = MarketContext.getMarketContext(symbolBars, "1Day",
            MarketContext.BenchmarkInput.ok(spyBars),
            MarketContext.BenchmarkInput.ok(qqqBars),
            MarketContext.BenchmarkInput.ok(iwmBars),
            null, null, MarketContext.BenchmarkInput.ok(null));

        Map<String, Object> expected = m(scenario, "result");
        Map<String, Object> sector = m(expected, "sector");
        assertThat(s(sector, "name")).as("unknownSector fixture ground truth: sector.name should also be null").isNull();
        assertThat(s(sector, "etf")).as("unknownSector fixture ground truth: sector.etf should also be null").isNull();
        assertThat(actual.sector().name()).as("unknownSector.sector.name").isNull();
        assertThat(actual.sector().etf()).as("unknownSector.sector.etf").isNull();
        assertThat(actual.sector().trend()).as("unknownSector.sector.trend").isNull();
        assertThat(actual.relativeStrengthVsSector()).as("unknownSector.relativeStrengthVsSector").isNull();
    }

    @Test
    void marketContextFetchFailureMatchesTypeScript() {
        Map<String, Object> scenario = marketContextScenario("fetchFailure");
        List<Bar> symbolBars = readBars(scenario.get("symbolBars"));
        Map<String, Object> benchmarkBars = m(scenario, "benchmarkBars");
        List<Bar> qqqBars = readBars(benchmarkBars.get("QQQ"));
        List<Bar> iwmBars = readBars(benchmarkBars.get("IWM"));

        // SPY's fetch fails in this scenario (real "simulated Alpaca outage" catch-block path) -
        // benchmarkTrend must report regime:null with the error text captured in `source`, and
        // relativeStrengthVsSPY must be null too (computeRelativeStrength's own catch path).
        MarketContext.Result actual = MarketContext.getMarketContext(symbolBars, "1Day",
            MarketContext.BenchmarkInput.failed("simulated Alpaca outage"),
            MarketContext.BenchmarkInput.ok(qqqBars),
            MarketContext.BenchmarkInput.ok(iwmBars),
            null, null, MarketContext.BenchmarkInput.ok(null));

        Map<String, Object> expected = m(scenario, "result");
        Map<String, Object> expectedSpy = m(expected, "spy");
        assertThat(actual.spy().regime()).as("fetchFailure.spy.regime").isNull();
        assertThat(actual.spy().source()).as("fetchFailure.spy.source").contains("simulated Alpaca outage")
            .isEqualTo(s(expectedSpy, "source"));
        assertThat(actual.relativeStrengthVsSPY()).as("fetchFailure.relativeStrengthVsSPY").isNull();
    }
}
